name: build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: pnpm install
        run: pnpm i --frozen-lockfile
      - name: build
        run: npm run build
      - name: deploy
        run: sh scripts/deploy.sh
        env:
          CODINGNET_USERNAME: ${{ secrets.CODINGNET_USERNAME }}
          CODINGNET_TOKEN: ${{ secrets.CODINGNET_TOKEN }}
          ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
