name: build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.11.0"
          github_token: ${{ github.token }}

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: build
        run: pnpm build

      - name: deploy
        run: sh scripts/deploy.sh
        env:
          CODINGNET_USERNAME: ${{ secrets.CODINGNET_USERNAME }}
          CODINGNET_TOKEN: ${{ secrets.CODINGNET_TOKEN }}
          ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
